# Generated by Django 4.0.1 on 2023-05-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0002_botapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('video_example', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_1', models.TextField(blank=True, null=True)),
                ('text_2', models.TextField(blank=True, null=True)),
                ('video_url', models.CharField(max_length=255)),
                ('program', models.FileField(upload_to='programs')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.FloatField(default=0.5)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StartStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='files')),
                ('name', models.CharField(max_length=255)),
                ('slide_title', models.CharField(max_length=255)),
                ('slide_text', models.CharField(max_length=255)),
                ('slide_image', models.FileField(upload_to='files')),
                ('abilitys', models.ManyToManyField(to='ApiApp.Ability')),
                ('start_step', models.ManyToManyField(to='ApiApp.StartStep')),
            ],
        ),
    ]
