# Generated by Django 4.0.1 on 2023-05-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0003_ability_contact_doc_pricing_queryanswer_startstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botapp',
            name='balans',
            field=models.FloatField(default=0.0),
        ),
    ]
