# Generated by Django 4.0.1 on 2023-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0004_botapp_balans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('command', models.CharField(max_length=255)),
            ],
        ),
    ]
